apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: null-value-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: null-value-test
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://github.com/Gladdstone/argo-test
    targetRevision: HEAD
    path: argo-test
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true